import { useEffect, useState } from "react";
import type { Assignment, Lead, ManagerScore } from "../types";
import { formatByn, formatPercent } from "../utils/formatters";

export function LeadDetailsDrawer({ lead, assignment, scores, loading, error, actionError, busy, onClose, onAssign, onRemove, onStartWork }: {
  lead: Lead | null; assignment?: Assignment; scores: ManagerScore[]; loading: boolean; error: string; actionError: string; busy: boolean;
  onClose: () => void; onAssign: (managerId: string) => void; onRemove: () => void; onStartWork: () => void;
}) {
  const [selectedId, setSelectedId] = useState("");
  useEffect(() => { setSelectedId(assignment?.managerId ?? ""); }, [lead?.id, assignment?.managerId]);
  if (!lead) return null;
  const ranked = [...scores].sort((a, b) => b.expectedGm - a.expectedGm);
  const recommended = ranked.find((item) => item.managerId === assignment?.recommendedManagerId);
  const assigned = ranked.find((item) => item.managerId === assignment?.managerId);
  const selected = ranked.find((item) => item.managerId === selectedId);
  const change = selected ? selected.expectedGm - (assigned?.expectedGm ?? 0) : 0;
  const cannotAssign = Boolean(selected && selected.managerId !== assignment?.managerId && selected.currentLoad >= selected.dailyCapacity);
  return <aside className="drawer" role="dialog" aria-label={`Заявка ${lead.id}`}>
    <div className="drawer-header"><div><span className="eyebrow">Заявка #{lead.id.replace("lead-", "")}</span><h2>{lead.region} · {lead.product}</h2></div><button className="button button-ghost" onClick={onClose} aria-label="Закрыть детали">Закрыть</button></div>
    <div className="detail-grid"><span>Источник</span><strong>{lead.source}</strong><span>Дата заявки</span><strong>{new Date(lead.createdAt).toLocaleString("ru-RU")}</strong><span>Дата переговоров</span><strong>{lead.plannedFor ?? "Не указана"}</strong><span>Потенциальная сумма</span><strong>{formatByn(lead.potentialAmount)}</strong><span>Состояние</span><strong>{assignment?.managerId ? lead.status === "in_progress" ? "В работе" : assignment.source === "manual" ? "Назначена вручную" : "Рекомендована" : "Без назначения"}</strong><span>Рекомендация системы</span><strong>{assignment?.recommendedManagerName ?? "Нет"}</strong><span>Текущее назначение</span><strong>{assignment?.currentManagerName ?? assigned?.managerName ?? "Нет"}</strong></div>
    <h3 className="section-label">Почему этот менеджер</h3>
    {loading && <p className="drawer-note">Загружаем расчёт…</p>}
    {error && <p className="form-error">{error}</p>}
    {recommended && <div className="recommendation-explainer"><strong>{recommended.managerName} · {formatByn(assignment?.recommendationSnapshot?.expectedGm ?? recommended.expectedGm)} ожидаемой GM при расчёте</strong><span>{assignment?.recommendationSnapshot?.explanation ?? recommended.explanation}</span><span>{assignment?.recommendationSnapshot ? `${formatPercent(assignment.recommendationSnapshot.probability)} × ${formatByn(assignment.recommendationSnapshot.expectedGrossMarginOnSale)} ≈ ${formatByn(assignment.recommendationSnapshot.expectedGm)}` : recommended.formula}</span><span>Снимок рекомендации: {assignment?.recommendationSnapshot ? new Date(assignment.recommendationSnapshot.calculatedAt).toLocaleString("ru-RU") : "не сохранён"}. Оценки альтернатив ниже рассчитаны по текущей истории.</span><span>История по этой связке сейчас: {recommended.observations} переговоров, {recommended.sales} продаж. За 14 дней: {recommended.recentObservations} переговоров, конверсия {formatPercent(recommended.recentConversion)}. Историческая конверсия: {formatPercent(recommended.historicalConversion)}.</span><span>Прогноз сглажен: {formatPercent(recommended.smoothingWeight)} личная история, {formatPercent(1 - recommended.smoothingWeight)} общие данные. Загрузка {recommended.currentLoad}/{recommended.dailyCapacity}.</span></div>}
    {assignment?.managerId && recommended && assignment.managerId !== recommended.managerId && <p className="drawer-note">Сотрудник изменил рекомендацию. Текущий менеджер: {assigned?.managerName ?? assignment.currentManagerName}.</p>}
    {assignment?.managerId && recommended && assignment.managerId === recommended.managerId && ranked[0]?.managerId !== recommended.managerId && <p className="drawer-note">У другого менеджера оценка этой заявки выше, но система оптимизировала весь план с учётом конкурирующих заявок и ограничений по местам. Ниже показаны все оценки и текущая загрузка.</p>}
    <h3 className="section-label">Сравнение менеджеров для этой заявки</h3>
    <p className="drawer-note">GM = вероятность продажи × GM успешной сделки. Чек и скидка показаны для проверки прогноза; скидка уже отражена в исторической GM.</p>
    <div className="comparison-list">{ranked.map((score) => <button type="button" key={score.managerId} className={`comparison-item ${selectedId === score.managerId ? "is-selected" : ""}`} onClick={() => setSelectedId(score.managerId)}><span className="comparison-title"><strong>{score.managerName}</strong><b>{formatByn(score.expectedGm)}</b></span><span>{score.formula} · мест {score.currentLoad}/{score.dailyCapacity}</span><span>Чек {formatByn(score.expectedSaleAmount)} · GM продажи {formatByn(score.expectedGrossMarginOnSale)} · средняя скидка {formatPercent(score.averageDiscount)}</span><span>{score.observations} переговоров / {score.sales} продаж по связке; 14/60/180 дней: {score.recentObservations}/{score.observations60}/{score.observations180}; вес личных данных {formatPercent(score.smoothingWeight)}</span><span>{score.explanation}</span></button>)}</div>
    {selected && <div className="decision-panel"><strong>Если выбрать {selected.managerName}</strong><span>Expected GM этой заявки: {formatByn(selected.expectedGm)}. Изменение относительно текущего назначения: {change >= 0 ? "+" : ""}{formatByn(change)}.</span><span>Загрузка после назначения: {selected.currentLoad + (selected.managerId === assignment?.managerId ? 0 : 1)}/{selected.dailyCapacity}.</span>{cannotAssign && <span className="form-error">Свободных мест нет. Выберите другого менеджера.</span>}<button type="button" className="button button-primary" disabled={busy || cannotAssign || selected.managerId === assignment?.managerId} onClick={() => onAssign(selected.managerId)}>Назначить выбранного</button></div>}
    {actionError && <p className="form-error">{actionError}</p>}
    <div className="drawer-actions">{assignment?.source === "optimization" && assignment.managerId && <button type="button" className="button button-primary" disabled={busy} onClick={() => onAssign(assignment.managerId!)}>Подтвердить рекомендацию</button>}{assignment?.managerId && <button type="button" className="button button-secondary" disabled={busy} onClick={onRemove} aria-label="Снять назначение">× Снять назначение</button>}{assignment?.managerId && lead.status !== "in_progress" && <button type="button" className="button button-secondary" disabled={busy} onClick={onStartWork}>В работу</button>}</div>
  </aside>;
}
