import type { BoardSnapshot, Lead, Manager, ManagerScore, Assignment, User } from "../types";
type Fetcher = typeof fetch;
// In production the API is served by a Netlify Function on the same domain.
// Vite proxies /api to the local backend during development.
const baseUrl = import.meta.env.VITE_API_URL ?? "";
export function createApiClient(fetcher: Fetcher = fetch, getToken: () => string | null = () => null, onUnauthorized: () => void = () => undefined) {
  async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const token = getToken(); const headers = new Headers(options.headers); headers.set("Content-Type", "application/json"); if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetcher(`${baseUrl}${path}`, { ...options, headers }); const body = await response.json().catch(() => ({})); if (response.status === 401) onUnauthorized(); if (!response.ok) throw new Error(body.error?.message ?? "Не удалось выполнить запрос"); return body as T; }
  return { login: (email: string, password: string) => request<{ token: string; user: User }>("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }), getBoard: (plannedFor?: string) => request<BoardSnapshot>(`/api/dashboard/summary${plannedFor ? `?plannedFor=${encodeURIComponent(plannedFor)}` : ""}`), getManagers: () => request<{ managers: Manager[] }>("/api/managers"), addManager: (input: Omit<Manager, "id" | "createdAt" | "active"> & { active?: boolean }) => request<Manager>("/api/managers", { method: "POST", body: JSON.stringify(input) }), addLead: (input: Omit<Lead, "id" | "createdAt" | "status"> & { status?: string }) => request<Lead>("/api/leads", { method: "POST", body: JSON.stringify(input) }), runOptimization: (plannedFor?: string) => request<{ assignedCount: number; expectedTotalGm: number }>("/api/optimization-runs", { method: "POST", body: JSON.stringify(plannedFor ? { plannedFor } : {}) }), assignLead: (leadId: string, managerId: string | null) => request<{ expectedGmDelta: number }>(`/api/leads/${leadId}/assignment`, { method: "PATCH", body: JSON.stringify({ managerId }) }), setLeadStatus: (leadId: string, status: "assigned" | "in_progress") => request<Lead>(`/api/leads/${leadId}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), getLeadDetail: (leadId: string) => request<{ lead: Lead; assignment: Assignment | null; scores: ManagerScore[] }>(`/api/leads/${leadId}`) };
}
export const api = createApiClient(fetch, () => sessionStorage.getItem("kanban-demo-token"), () => { sessionStorage.removeItem("kanban-demo-token"); });
